<?php
// rss.php — Scroll News internal RSS endpoint backed by the articles table
// Usage: /rss.php?category=Politics
// V1: category only, limit fixed to rss.app-ish count (50)

declare(strict_types=1);

ini_set('display_errors', '1');
ini_set('display_startup_errors', '0');
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
ini_set('log_errors', '1');

// --- Config ---
$LIMIT = 50;

// If you want to keep this internal-only, set RSS_KEY in env and require ?key=...
// $RSS_KEY = getenv('RSS_KEY') ?: '';
// if ($RSS_KEY !== '' && (($_GET['key'] ?? '') !== $RSS_KEY)) {
//   http_response_code(403);
//   header('Content-Type: text/plain; charset=utf-8');
//   echo "Forbidden\n";
//   exit;
// }

// --- Helpers ---
function sn_xml_cdata(string $s): string {
  // RSS CDATA cannot contain "]]>"
  return '<![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $s) . ']]>';
}

function sn_rfc2822_gmt($ts): string {
  // Accepts DateTimeInterface or string
  try {
    if ($ts instanceof DateTimeInterface) {
      $dt = (new DateTimeImmutable($ts->format('c')))->setTimezone(new DateTimeZone('GMT'));
    } else {
      $dt = (new DateTimeImmutable((string)$ts))->setTimezone(new DateTimeZone('GMT'));
    }
  } catch (Throwable $e) {
    $dt = (new DateTimeImmutable('now', new DateTimeZone('GMT')));
  }
  return $dt->format('D, d M Y H:i:s') . ' GMT';
}

function sn_guess_site_url(): string {
  $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
  $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
  return $scheme . '://' . $host;
}

function sn_short_blurb(?string $text, int $max = 240): string {
  $t = trim((string)$text);
  if ($t === '') return '';
  $t = preg_replace('/\s+/', ' ', strip_tags($t));
  if (mb_strlen($t) <= $max) return $t;
  return mb_substr($t, 0, $max - 1) . '…';
}

// --- Input ---
$category = trim((string)($_GET['category'] ?? ''));
if ($category === '') {
  http_response_code(400);
  header('Content-Type: text/plain; charset=utf-8');
  echo "Missing required parameter: category\n";
  exit;
}

// Normalize category for display + query
$category_display = $category;

// Optional: whitelist categories (recommended)
// $allowed = ['Politics','Business','Tech','Science','Sports','World','Health','Entertainment'];
// $catNorm = ucfirst(strtolower($category));
// if (!in_array($catNorm, $allowed, true)) { ... }

$siteUrl  = sn_guess_site_url();
$selfUrl  = $siteUrl . ($_SERVER['REQUEST_URI'] ?? '/rss.php');
$nowGmt   = sn_rfc2822_gmt('now');

// --- DB ---
define('BASE_PATH', __DIR__);
require_once BASE_PATH . "/core/___modules.php";
$pdo = _pdo_or_null();

if (!$pdo) {
  http_response_code(500);
  header('Content-Type: text/plain; charset=utf-8');
  echo "DB connection not available\n";
  exit;
}

/*
  TODO: Map these to your articles table columns.

  Expected output fields:
  - title
  - link (canonical story url)
  - pub_date (timestamp)
  - creator (publisher/author)
  - image_url
  - summary (short text)
*/
$sql = "
  SELECT
    a.title            AS title,
    a.url              AS link,
    a.pub_date         AS pub_date,
    COALESCE(a.author, a.source_slug, 'Scroll News') AS creator,
    a.media_url AS image_url,
    a.description AS summary
  FROM articles a
  WHERE
    a.title IS NOT NULL
    AND a.url IS NOT NULL
    AND a.pub_date IS NOT NULL
    AND LOWER(a.source_slug) = LOWER(:category)
    AND a.deleted_at IS NULL
  ORDER BY a.pub_date DESC
  LIMIT {$LIMIT}
";

$stmt = $pdo->prepare($sql);
$stmt->execute([':category' => $category]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

// --- Build RSS ---
header('Content-Type: application/rss+xml; charset=utf-8');

echo '<?xml version="1.0" encoding="UTF-8"?>';
echo '<rss version="2.0" '
  . 'xmlns:dc="http://purl.org/dc/elements/1.1/" '
  . 'xmlns:content="http://purl.org/rss/1.0/modules/content/" '
  . 'xmlns:atom="http://www.w3.org/2005/Atom" '
  . 'xmlns:media="http://search.yahoo.com/mrss/">';

echo '<channel>';

echo '<title>' . sn_xml_cdata($category_display) . '</title>';
echo '<description>' . sn_xml_cdata('#' . preg_replace('/\s+/', '', $category_display) . ' generated by Scroll News') . '</description>';
echo '<link>' . htmlspecialchars($siteUrl, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</link>';
echo '<generator>' . htmlspecialchars($siteUrl, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</generator>';
echo '<lastBuildDate>' . htmlspecialchars($nowGmt, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</lastBuildDate>';
echo '<atom:link href="' . htmlspecialchars($selfUrl, ENT_QUOTES | ENT_XML1, 'UTF-8') . '" rel="self" type="application/rss+xml"/>';
echo '<language>' . sn_xml_cdata('en') . '</language>';

foreach ($rows as $r) {
  $title   = (string)($r['title'] ?? '');
  $link    = (string)($r['link'] ?? '');
  $creator = (string)($r['creator'] ?? 'Scroll News');
  $img     = (string)($r['image_url'] ?? '');
  $summary = (string)($r['summary'] ?? '');
  $pubDate = sn_rfc2822_gmt($r['pub_date'] ?? 'now');

  if ($title === '' || $link === '') continue;

  // rss.app uses a non-permalink guid that looks like md5
  $guid = md5($link);

  // description: mimic rss.app style (image + short blurb inside a div)
  $descHtml = '';
  if ($img !== '') {
    $descHtml .= '<div><img src="' . htmlspecialchars($img, ENT_QUOTES, 'UTF-8') . '" style="width: 100%;" />';
  } else {
    $descHtml .= '<div>';
  }

  $blurb = sn_short_blurb($summary, 260);
  if ($blurb !== '') {
    $descHtml .= '<div>' . htmlspecialchars($blurb, ENT_QUOTES, 'UTF-8') . '</div>';
  }
  $descHtml .= '</div>';

  echo '<item>';
  echo '<title>' . sn_xml_cdata($title) . '</title>';
  echo '<description>' . sn_xml_cdata($descHtml) . '</description>';
  echo '<link>' . htmlspecialchars($link, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</link>';
  echo '<guid isPermaLink="false">' . htmlspecialchars($guid, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</guid>';
  echo '<dc:creator>' . sn_xml_cdata($creator) . '</dc:creator>';
  echo '<pubDate>' . htmlspecialchars($pubDate, ENT_QUOTES | ENT_XML1, 'UTF-8') . '</pubDate>';

  if ($img !== '') {
    echo '<media:content medium="image" url="' . htmlspecialchars($img, ENT_QUOTES | ENT_XML1, 'UTF-8') . '"/>';
  }

  echo '</item>';
}

echo '</channel></rss>';