<?php

define('BASE_PATH', dirname(__DIR__));

require_once BASE_PATH . '/auth/includes/require_auth.php';
require_once BASE_PATH . '/auth/includes/auth_db.php';

$userId = $_SESSION['user_id'] ?? null;
$userEmail = trim((string)($_SESSION['user_email'] ?? ''));
$displayName = trim((string)($_SESSION['display_name'] ?? ''));

if (empty($_SESSION['publisher_pro_csrf'])) {
    $_SESSION['publisher_pro_csrf'] = bin2hex(random_bytes(32));
}

$errors = [];

$form = [
    'publication_name' => '',
    'website_url' => '',
    'contact_name' => $displayName,
    'email' => $userEmail,
    'publisher_type' => '',
    'monthly_audience' => '',
    'services' => [],
    'message' => '',
];

$serviceOptions = [
    'Publisher verification',
    'RSS feed onboarding',
    'Attribution and metadata review',
    'Content rights and removals',
    'Featured publisher profile',
    'Priority publisher support',
];

function publisher_pro_h($value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $form['publication_name'] = trim((string)($_POST['publication_name'] ?? ''));
    $form['website_url'] = trim((string)($_POST['website_url'] ?? ''));
    $form['contact_name'] = trim((string)($_POST['contact_name'] ?? ''));
    $form['email'] = trim((string)($_POST['email'] ?? ''));
    $form['publisher_type'] = trim((string)($_POST['publisher_type'] ?? ''));
    $form['monthly_audience'] = trim((string)($_POST['monthly_audience'] ?? ''));
    $form['services'] = array_values(array_intersect(
        $serviceOptions,
        is_array($_POST['services'] ?? null) ? $_POST['services'] : []
    ));
    $form['message'] = trim((string)($_POST['message'] ?? ''));

    $csrfToken = (string)($_POST['csrf_token'] ?? '');

    if (!hash_equals($_SESSION['publisher_pro_csrf'], $csrfToken)) {
        $errors[] = 'Your session expired. Please refresh the page and try again.';
    }

    if ($form['publication_name'] === '') {
        $errors[] = 'Please enter the publication or organization name.';
    }

    if ($form['website_url'] === '' || !filter_var($form['website_url'], FILTER_VALIDATE_URL)) {
        $errors[] = 'Please enter a valid website URL, including https://.';
    }

    if ($form['contact_name'] === '') {
        $errors[] = 'Please enter a contact name.';
    }

    if ($form['email'] === '' || !filter_var($form['email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Please enter a valid email address.';
    }

    if (!in_array($form['publisher_type'], [
        'Independent publisher',
        'Local or regional publisher',
        'Digital media company',
        'Newsletter or creator publication',
        'Other',
    ], true)) {
        $errors[] = 'Please select a publisher type.';
    }

    if (!$errors) {
        $pdo = auth_db();

        $pdo->exec("
            CREATE TABLE IF NOT EXISTS publisher_pro_applications (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT,
                publication_name VARCHAR(160) NOT NULL,
                website_url TEXT NOT NULL,
                contact_name VARCHAR(120) NOT NULL,
                email VARCHAR(254) NOT NULL,
                publisher_type VARCHAR(100) NOT NULL,
                monthly_audience VARCHAR(100),
                services JSONB,
                message TEXT,
                status VARCHAR(30) NOT NULL DEFAULT 'new',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        ");

        $stmt = $pdo->prepare("
            INSERT INTO publisher_pro_applications (
                user_id,
                publication_name,
                website_url,
                contact_name,
                email,
                publisher_type,
                monthly_audience,
                services,
                message
            ) VALUES (
                :user_id,
                :publication_name,
                :website_url,
                :contact_name,
                :email,
                :publisher_type,
                :monthly_audience,
                CAST(:services AS JSONB),
                :message
            )
        ");

        $stmt->execute([
            ':user_id' => $userId,
            ':publication_name' => $form['publication_name'],
            ':website_url' => $form['website_url'],
            ':contact_name' => $form['contact_name'],
            ':email' => $form['email'],
            ':publisher_type' => $form['publisher_type'],
            ':monthly_audience' => $form['monthly_audience'] !== '' ? $form['monthly_audience'] : null,
            ':services' => $form['services']
                ? json_encode($form['services'], JSON_UNESCAPED_SLASHES)
                : null,
            ':message' => $form['message'] !== '' ? $form['message'] : null,
        ]);

        $_SESSION['publisher_pro_csrf'] = bin2hex(random_bytes(32));

        header('Location: /publisher-pro/?applied=1');
        exit;
    }
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <?php require_once BASE_PATH . '/views/partials/___google_analytics.php'; ?>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta
        name="description"
        content="Publisher Pro provides hands-on onboarding, verification, feed support, attribution review, and priority assistance for publishers on Scroll News." />
    <meta name="author" content="Scroll News" />

    <title>Publisher Pro — Scroll News</title>

    <link rel="canonical" href="https://scrollnews.ai/publisher-pro/" />
    <link rel="icon" type="image/png" href="/assets/img/play-green.png" />

    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://scrollnews.ai/publisher-pro/" />
    <meta property="og:title" content="Publisher Pro — Scroll News" />
    <meta
        property="og:description"
        content="Hands-on publisher onboarding, verification, distribution support, and priority assistance from Scroll News." />
    <meta property="og:image" content="https://scrollnews.ai/assets/img/og/og-scrollnews-home-1200x630.png" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Publisher Pro — Scroll News" />
    <meta
        name="twitter:description"
        content="Hands-on publisher onboarding, verification, distribution support, and priority assistance from Scroll News." />
    <meta name="twitter:image" content="https://scrollnews.ai/assets/img/og/og-scrollnews-home-1200x630.png" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v6.7.2/js/all.js" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&family=Open+Sans&display=swap" rel="stylesheet" />

    <link href="/assets/css/styles.css?v=<?= filemtime(BASE_PATH . '/assets/css/styles.css'); ?>" rel="stylesheet" />
    <link href="/assets/css/custom.css?v=<?= filemtime(BASE_PATH . '/assets/css/custom.css'); ?>" rel="stylesheet" />
    <link href="/assets/css/auth.css?v=<?= filemtime(BASE_PATH . '/assets/css/auth.css'); ?>" rel="stylesheet" />
    <link href="/assets/css/account.css?v=<?= filemtime(BASE_PATH . '/assets/css/account.css'); ?>" rel="stylesheet" />

    <style>
        .publisher-pro-hero {
            background: linear-gradient(135deg, rgba(40, 167, 69, 0.12), rgba(255, 255, 255, 0));
            border: 1px solid rgba(40, 167, 69, 0.2);
        }

        .publisher-pro-icon {
            width: 44px;
            height: 44px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            border-radius: 50%;
            background: rgba(40, 167, 69, 0.12);
            color: #218838;
            font-size: 1.15rem;
            flex-shrink: 0;
        }

        .publisher-pro-feature {
            display: flex;
            gap: 0.9rem;
            align-items: flex-start;
        }

        .publisher-pro-feature h3 {
            font-size: 1rem;
            margin-bottom: 0.25rem;
        }

        .publisher-pro-section-title {
            max-width: 680px;
            margin-left: auto;
            margin-right: auto;
        }

        .publisher-pro-application {
            scroll-margin-top: 90px;
        }

        .publisher-pro-checklist {
            padding-left: 0;
            list-style: none;
        }

        .publisher-pro-checklist li {
            margin-bottom: 0.7rem;
        }

        .publisher-pro-checklist .fa-check {
            color: #28a745;
            margin-right: 0.55rem;
        }

        #included {
            scroll-margin-top: 90px;
        }
    </style>
</head>

<body id="page-top" class="auth-page account-page">

    <div class="page">

        <?php require_once BASE_PATH . '/views/partials/___topnav_full.php'; ?>

        <main class="auth-shell container my-5">
            <div class="auth-card card border-0 rounded-3">
                <div class="card-body p-4 p-md-5">

                    <section class="publisher-pro-hero rounded p-4 p-md-5 mb-4 text-center">
                        <img
                            src="/assets/img/play-green.png"
                            alt="Scroll News"
                            class="auth-logo mb-3"
                            style="height: 52px; width: auto;" />

                        <div class="mb-2">
                            <span class="badge badge-success">Now accepting applications</span>
                        </div>

                        <h1 class="display-4 font-weight-bold mb-3">Publisher Pro</h1>

                        <p class="lead text-muted mx-auto mb-4" style="max-width: 760px;">
                            Hands-on support for publishers that want stronger attribution,
                            cleaner distribution, and a direct relationship with Scroll News.
                        </p>

                        <a href="#apply" class="btn btn-primary btn-lg mr-sm-2 mb-2" data-loading>
                            Apply for Publisher Pro
                        </a>

                        <a href="#included" class="btn btn-outline-secondary btn-lg mb-2">
                            See What’s Included
                        </a>
                    </section>

                    <section class="py-4">
                        <div class="text-center publisher-pro-section-title mb-4">
                            <h2 class="h3 mb-2">A direct path for serious publishers</h2>
                            <p class="text-muted mb-0">
                                Publisher Pro is the assisted service layer for organizations that need
                                support before the full self-service Publisher Tools platform launches.
                            </p>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body publisher-pro-feature">
                                        <span class="publisher-pro-icon">
                                            <i class="fa-solid fa-circle-check"></i>
                                        </span>
                                        <div>
                                            <h3>Publisher verification</h3>
                                            <p class="text-muted mb-0">
                                                Establish your publication’s identity and primary domains with Scroll News.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body publisher-pro-feature">
                                        <span class="publisher-pro-icon">
                                            <i class="fa-solid fa-rss"></i>
                                        </span>
                                        <div>
                                            <h3>RSS and feed onboarding</h3>
                                            <p class="text-muted mb-0">
                                                Get help reviewing feeds, metadata, article links, and ingestion readiness.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body publisher-pro-feature">
                                        <span class="publisher-pro-icon">
                                            <i class="fa-solid fa-link"></i>
                                        </span>
                                        <div>
                                            <h3>Attribution support</h3>
                                            <p class="text-muted mb-0">
                                                Help us keep publication names, source links, and article metadata accurate.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body publisher-pro-feature">
                                        <span class="publisher-pro-icon">
                                            <i class="fa-solid fa-headset"></i>
                                        </span>
                                        <div>
                                            <h3>Priority assistance</h3>
                                            <p class="text-muted mb-0">
                                                Reach the Scroll News team about corrections, removals, rights, and distribution questions.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <section id="included" class="py-4">
                        <div class="row align-items-stretch">
                            <div class="col-lg-7 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body p-4">
                                        <h2 class="h4 mb-3">What Publisher Pro includes</h2>

                                        <ul class="publisher-pro-checklist text-muted mb-0">
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                Guided publisher onboarding and account review
                                            </li>
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                Publication, domain, and feed verification
                                            </li>
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                RSS, metadata, and attribution review
                                            </li>
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                Assistance with corrections and article removal requests
                                            </li>
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                Publisher profile preparation as profiles become available
                                            </li>
                                            <li>
                                                <i class="fa-solid fa-check"></i>
                                                Priority communication with the Scroll News team
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-5 mb-3">
                                <div class="card h-100 border-0 shadow-sm">
                                    <div class="card-body p-4">
                                        <span class="badge badge-light mb-2">Early access</span>
                                        <h2 class="h4 mb-3">Built around your publication</h2>
                                        <p class="text-muted">
                                            Publisher Pro is currently offered through a guided application process.
                                            We review each publication individually and determine the most useful next steps.
                                        </p>
                                        <p class="text-muted mb-0">
                                            Pricing and service scope are discussed after the initial review.
                                            Submitting an application does not create a paid commitment.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <section id="apply" class="publisher-pro-application py-4">
                        <div class="card border-0 shadow-sm">
                            <div class="card-body p-4 p-md-5">

                                <?php if (isset($_GET['applied'])): ?>
                                    <div class="alert alert-success auth-alert mb-4" role="alert">
                                        <strong>Application submitted successfully! 🎉</strong>
                                        Thank you for your interest in Publisher Pro. We'll review your publication and contact you by email if we need any additional information.
                                    </div>
                                <?php endif; ?>

                                <div class="row">
                                    <div class="col-lg-4 mb-4 mb-lg-0">
                                        <span class="badge badge-success mb-2">Publisher application</span>
                                        <h2 class="h3 mb-3">Tell us about your publication</h2>
                                        <p class="text-muted">
                                            Share a few details about your organization and the support you’re looking for.
                                        </p>
                                        <p class="small text-muted mb-0">
                                            You’re applying as
                                            <strong><?= publisher_pro_h($userEmail); ?></strong>.
                                        </p>
                                    </div>

                                    <div class="col-lg-8">
                                        <?php if ($errors): ?>
                                            <div class="alert alert-danger" role="alert">
                                                <strong>Please review the following:</strong>
                                                <ul class="mb-0 mt-2">
                                                    <?php foreach ($errors as $error): ?>
                                                        <li><?= publisher_pro_h($error); ?></li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        <?php endif; ?>

                                        <form method="post" action="/publisher-pro/#apply">
                                            <input
                                                type="hidden"
                                                name="csrf_token"
                                                value="<?= publisher_pro_h($_SESSION['publisher_pro_csrf']); ?>" />

                                            <div class="form-group">
                                                <label for="publication_name">
                                                    Publication or organization name
                                                    <span class="text-danger" aria-hidden="true">*</span>
                                                    <span class="sr-only">Required</span>
                                                </label>
                                                <input
                                                    type="text"
                                                    class="form-control"
                                                    id="publication_name"
                                                    name="publication_name"
                                                    maxlength="160"
                                                    value="<?= publisher_pro_h($form['publication_name']); ?>"
                                                    required />
                                            </div>

                                            <div class="form-group">
                                                <label for="website_url">
                                                    Publication website
                                                    <span class="text-danger" aria-hidden="true">*</span>
                                                    <span class="sr-only">Required</span>
                                                </label>
                                                <input
                                                    type="url"
                                                    class="form-control"
                                                    id="website_url"
                                                    name="website_url"
                                                    placeholder="https://example.com"
                                                    maxlength="500"
                                                    value="<?= publisher_pro_h($form['website_url']); ?>"
                                                    required />
                                            </div>

                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <label for="contact_name">
                                                        Contact name
                                                        <span class="text-danger" aria-hidden="true">*</span>
                                                        <span class="sr-only">Required</span>
                                                    </label>
                                                    <input
                                                        type="text"
                                                        class="form-control"
                                                        id="contact_name"
                                                        name="contact_name"
                                                        maxlength="120"
                                                        value="<?= publisher_pro_h($form['contact_name']); ?>"
                                                        required />
                                                </div>

                                                <div class="form-group col-md-6">
                                                    <label for="email">
                                                        Contact email
                                                        <span class="text-danger" aria-hidden="true">*</span>
                                                        <span class="sr-only">Required</span>
                                                    </label>
                                                    <input
                                                        type="email"
                                                        class="form-control"
                                                        id="email"
                                                        name="email"
                                                        maxlength="254"
                                                        value="<?= publisher_pro_h($form['email']); ?>"
                                                        required />
                                                </div>
                                            </div>

                                            <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <label for="publisher_type">
                                                        Publisher type
                                                        <span class="text-danger" aria-hidden="true">*</span>
                                                        <span class="sr-only">Required</span>
                                                    </label>
                                                    <select
                                                        class="form-control"
                                                        id="publisher_type"
                                                        name="publisher_type"
                                                        required>
                                                        <option value="">Select one</option>
                                                        <?php foreach (
                                                            [
                                                                'Independent publisher',
                                                                'Local or regional publisher',
                                                                'Digital media company',
                                                                'Newsletter or creator publication',
                                                                'Other',
                                                            ] as $publisherType
                                                        ): ?>
                                                            <option
                                                                value="<?= publisher_pro_h($publisherType); ?>"
                                                                <?= $form['publisher_type'] === $publisherType ? 'selected' : ''; ?>>
                                                                <?= publisher_pro_h($publisherType); ?>
                                                            </option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>

                                                <div class="form-group col-md-6">
                                                    <label for="monthly_audience">
                                                        Approximate monthly audience
                                                        <span class="text-muted">(optional)</span>
                                                    </label>
                                                    <select
                                                        class="form-control"
                                                        id="monthly_audience"
                                                        name="monthly_audience">
                                                        <option value="">Prefer not to say</option>
                                                        <?php foreach (
                                                            [
                                                                'Under 10,000',
                                                                '10,000–99,999',
                                                                '100,000–999,999',
                                                                '1 million or more',
                                                                'Not yet launched',
                                                            ] as $audienceRange
                                                        ): ?>
                                                            <option
                                                                value="<?= publisher_pro_h($audienceRange); ?>"
                                                                <?= $form['monthly_audience'] === $audienceRange ? 'selected' : ''; ?>>
                                                                <?= publisher_pro_h($audienceRange); ?>
                                                            </option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <fieldset class="form-group">
                                                <legend class="col-form-label pt-0">
                                                    What are you interested in?
                                                    <span class="text-muted">(optional)</span>
                                                </legend>

                                                <div class="row">
                                                    <?php foreach ($serviceOptions as $index => $service): ?>
                                                        <div class="col-md-6">
                                                            <div class="custom-control custom-checkbox mb-2">
                                                                <input
                                                                    type="checkbox"
                                                                    class="custom-control-input"
                                                                    id="service_<?= $index; ?>"
                                                                    name="services[]"
                                                                    value="<?= publisher_pro_h($service); ?>"
                                                                    <?= in_array($service, $form['services'], true) ? 'checked' : ''; ?> />
                                                                <label
                                                                    class="custom-control-label"
                                                                    for="service_<?= $index; ?>">
                                                                    <?= publisher_pro_h($service); ?>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </div>
                                            </fieldset>

                                            <div class="form-group">
                                                <label for="message">
                                                    What would you like help with?
                                                    <span class="text-muted">(optional)</span>
                                                </label>
                                                <textarea
                                                    class="form-control"
                                                    id="message"
                                                    name="message"
                                                    rows="5"
                                                    maxlength="3000"
                                                    placeholder="Tell us about your publication, feeds, goals, or any current issues."><?= publisher_pro_h($form['message']); ?></textarea>
                                            </div>

                                            <button type="submit" class="btn btn-primary btn-lg">
                                                Submit Application
                                            </button>

                                            <p class="small text-muted mt-3 mb-0">
                                                By submitting, you authorize Scroll News to contact you about Publisher Pro.
                                            </p>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <hr class="my-4" />

                    <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center">
                        <a href="/account/" class="text-muted mb-3 mb-sm-0">← Back to Your Account</a>
                        <a href="/" class="btn btn-outline-secondary btn-sm">Return to Scroll News</a>
                    </div>

                </div>
            </div>
        </main>

        <?php require_once BASE_PATH . '/views/partials/___footer.php'; ?>

    </div>

    <?php require_once BASE_PATH . '/views/partials/___modals.php'; ?>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

</body>

</html>